import { rems } from './utils';

export default {
"m0": {
            margin: rems(0)
          },"m8": {
            margin: rems(8)
          },"m16": {
            margin: rems(16)
          },"m24": {
            margin: rems(24)
          },"m32": {
            margin: rems(32)
          },"m64": {
            margin: rems(64)
          },"m96": {
            margin: rems(96)
          },"m128": {
            margin: rems(128)
          },"m160": {
            margin: rems(160)
          },"m192": {
            margin: rems(192)
          },
"mt0": {
          marginTop: rems(0)
        },"mt8": {
          marginTop: rems(8)
        },"mt16": {
          marginTop: rems(16)
        },"mt24": {
          marginTop: rems(24)
        },"mt32": {
          marginTop: rems(32)
        },"mt64": {
          marginTop: rems(64)
        },"mt96": {
          marginTop: rems(96)
        },"mt128": {
          marginTop: rems(128)
        },"mt160": {
          marginTop: rems(160)
        },"mt192": {
          marginTop: rems(192)
        },
"mr0": {
          marginRight: rems(0)
        },"mr8": {
          marginRight: rems(8)
        },"mr16": {
          marginRight: rems(16)
        },"mr24": {
          marginRight: rems(24)
        },"mr32": {
          marginRight: rems(32)
        },"mr64": {
          marginRight: rems(64)
        },"mr96": {
          marginRight: rems(96)
        },"mr128": {
          marginRight: rems(128)
        },"mr160": {
          marginRight: rems(160)
        },"mr192": {
          marginRight: rems(192)
        },
"mb0": {
          marginBottom: rems(0)
        },"mb8": {
          marginBottom: rems(8)
        },"mb16": {
          marginBottom: rems(16)
        },"mb24": {
          marginBottom: rems(24)
        },"mb32": {
          marginBottom: rems(32)
        },"mb64": {
          marginBottom: rems(64)
        },"mb96": {
          marginBottom: rems(96)
        },"mb128": {
          marginBottom: rems(128)
        },"mb160": {
          marginBottom: rems(160)
        },"mb192": {
          marginBottom: rems(192)
        },
"ml0": {
          marginLeft: rems(0)
        },"ml8": {
          marginLeft: rems(8)
        },"ml16": {
          marginLeft: rems(16)
        },"ml24": {
          marginLeft: rems(24)
        },"ml32": {
          marginLeft: rems(32)
        },"ml64": {
          marginLeft: rems(64)
        },"ml96": {
          marginLeft: rems(96)
        },"ml128": {
          marginLeft: rems(128)
        },"ml160": {
          marginLeft: rems(160)
        },"ml192": {
          marginLeft: rems(192)
        },
"mx0": {
              marginLeft: rems(0),
              marginRight: rems(0)
            },"mx8": {
              marginLeft: rems(8),
              marginRight: rems(8)
            },"mx16": {
              marginLeft: rems(16),
              marginRight: rems(16)
            },"mx24": {
              marginLeft: rems(24),
              marginRight: rems(24)
            },"mx32": {
              marginLeft: rems(32),
              marginRight: rems(32)
            },"mx64": {
              marginLeft: rems(64),
              marginRight: rems(64)
            },"mx96": {
              marginLeft: rems(96),
              marginRight: rems(96)
            },"mx128": {
              marginLeft: rems(128),
              marginRight: rems(128)
            },"mx160": {
              marginLeft: rems(160),
              marginRight: rems(160)
            },"mx192": {
              marginLeft: rems(192),
              marginRight: rems(192)
            },
"my0": {
              marginTop: rems(0),
              marginBottom: rems(0)
            },"my8": {
              marginTop: rems(8),
              marginBottom: rems(8)
            },"my16": {
              marginTop: rems(16),
              marginBottom: rems(16)
            },"my24": {
              marginTop: rems(24),
              marginBottom: rems(24)
            },"my32": {
              marginTop: rems(32),
              marginBottom: rems(32)
            },"my64": {
              marginTop: rems(64),
              marginBottom: rems(64)
            },"my96": {
              marginTop: rems(96),
              marginBottom: rems(96)
            },"my128": {
              marginTop: rems(128),
              marginBottom: rems(128)
            },"my160": {
              marginTop: rems(160),
              marginBottom: rems(160)
            },"my192": {
              marginTop: rems(192),
              marginBottom: rems(192)
            },
"p0": {
            padding: rems(0)
          },"p8": {
            padding: rems(8)
          },"p16": {
            padding: rems(16)
          },"p24": {
            padding: rems(24)
          },"p32": {
            padding: rems(32)
          },"p64": {
            padding: rems(64)
          },"p96": {
            padding: rems(96)
          },"p128": {
            padding: rems(128)
          },"p160": {
            padding: rems(160)
          },"p192": {
            padding: rems(192)
          },
"pt0": {
          paddingTop: rems(0)
        },"pt8": {
          paddingTop: rems(8)
        },"pt16": {
          paddingTop: rems(16)
        },"pt24": {
          paddingTop: rems(24)
        },"pt32": {
          paddingTop: rems(32)
        },"pt64": {
          paddingTop: rems(64)
        },"pt96": {
          paddingTop: rems(96)
        },"pt128": {
          paddingTop: rems(128)
        },"pt160": {
          paddingTop: rems(160)
        },"pt192": {
          paddingTop: rems(192)
        },
"pr0": {
          paddingRight: rems(0)
        },"pr8": {
          paddingRight: rems(8)
        },"pr16": {
          paddingRight: rems(16)
        },"pr24": {
          paddingRight: rems(24)
        },"pr32": {
          paddingRight: rems(32)
        },"pr64": {
          paddingRight: rems(64)
        },"pr96": {
          paddingRight: rems(96)
        },"pr128": {
          paddingRight: rems(128)
        },"pr160": {
          paddingRight: rems(160)
        },"pr192": {
          paddingRight: rems(192)
        },
"pb0": {
          paddingBottom: rems(0)
        },"pb8": {
          paddingBottom: rems(8)
        },"pb16": {
          paddingBottom: rems(16)
        },"pb24": {
          paddingBottom: rems(24)
        },"pb32": {
          paddingBottom: rems(32)
        },"pb64": {
          paddingBottom: rems(64)
        },"pb96": {
          paddingBottom: rems(96)
        },"pb128": {
          paddingBottom: rems(128)
        },"pb160": {
          paddingBottom: rems(160)
        },"pb192": {
          paddingBottom: rems(192)
        },
"pl0": {
          paddingLeft: rems(0)
        },"pl8": {
          paddingLeft: rems(8)
        },"pl16": {
          paddingLeft: rems(16)
        },"pl24": {
          paddingLeft: rems(24)
        },"pl32": {
          paddingLeft: rems(32)
        },"pl64": {
          paddingLeft: rems(64)
        },"pl96": {
          paddingLeft: rems(96)
        },"pl128": {
          paddingLeft: rems(128)
        },"pl160": {
          paddingLeft: rems(160)
        },"pl192": {
          paddingLeft: rems(192)
        },
"px0": {
              paddingLeft: rems(0),
              paddingRight: rems(0)
            },"px8": {
              paddingLeft: rems(8),
              paddingRight: rems(8)
            },"px16": {
              paddingLeft: rems(16),
              paddingRight: rems(16)
            },"px24": {
              paddingLeft: rems(24),
              paddingRight: rems(24)
            },"px32": {
              paddingLeft: rems(32),
              paddingRight: rems(32)
            },"px64": {
              paddingLeft: rems(64),
              paddingRight: rems(64)
            },"px96": {
              paddingLeft: rems(96),
              paddingRight: rems(96)
            },"px128": {
              paddingLeft: rems(128),
              paddingRight: rems(128)
            },"px160": {
              paddingLeft: rems(160),
              paddingRight: rems(160)
            },"px192": {
              paddingLeft: rems(192),
              paddingRight: rems(192)
            },
"py0": {
              paddingTop: rems(0),
              paddingBottom: rems(0)
            },"py8": {
              paddingTop: rems(8),
              paddingBottom: rems(8)
            },"py16": {
              paddingTop: rems(16),
              paddingBottom: rems(16)
            },"py24": {
              paddingTop: rems(24),
              paddingBottom: rems(24)
            },"py32": {
              paddingTop: rems(32),
              paddingBottom: rems(32)
            },"py64": {
              paddingTop: rems(64),
              paddingBottom: rems(64)
            },"py96": {
              paddingTop: rems(96),
              paddingBottom: rems(96)
            },"py128": {
              paddingTop: rems(128),
              paddingBottom: rems(128)
            },"py160": {
              paddingTop: rems(160),
              paddingBottom: rems(160)
            },"py192": {
              paddingTop: rems(192),
              paddingBottom: rems(192)
            }}